chore: add react-dom for windows build
Somehow this only fails on Windows CI

```
info Using tsconfig paths for react-docgen
Failed to resolve dependency: react-dom/test-utils, present in client 'optimizeDeps.include'
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: listen EACCES: permission denied ::1:63315
 ❯ __node_internal_captureLargerStackTrace node:internal/errors:496:5
 ❯ __node_internal_uvExceptionWithHostPort node:internal/errors:593:12
 ❯ Server.setupListenHandle [as _listen2] node:net:1800:21
 ❯ listenInCluster node:net:1865:12
 ❯ GetAddrInfoReqWrap.doListen [as callback] node:net:2014:7
 ❯ GetAddrInfoReqWrap.onlookup [as oncomplete] node:dns:109:8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'EACCES', errno: -4092, syscall: 'listen', address: '::1', port: 63315 }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```